<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="373" started-at="2021-04-19T13:58:31 IST" finished-at="2021-04-19T13:58:31 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="373" started-at="2021-04-19T13:58:31 IST" finished-at="2021-04-19T13:58:31 IST">
      <class name="test.ReportGen">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:test.ReportGen@101eaf6]" name="beforeClass" is-config="true" duration-ms="111" started-at="2021-04-19T13:58:31 IST" finished-at="2021-04-19T13:58:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="Transaction()[pri:0, instance:test.ReportGen@101eaf6]" name="Transaction" duration-ms="11" started-at="2021-04-19T13:58:31 IST" finished-at="2021-04-19T13:58:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Transaction -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:test.ReportGen@101eaf6]" name="getResult" is-config="true" duration-ms="4" started-at="2021-04-19T13:58:31 IST" finished-at="2021-04-19T13:58:31 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Transaction status=SUCCESS method=ReportGen.Transaction()[pri:0, instance:test.ReportGen@101eaf6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="VerifyTransaction()[pri:0, instance:test.ReportGen@101eaf6]" name="VerifyTransaction" duration-ms="3" started-at="2021-04-19T13:58:31 IST" finished-at="2021-04-19T13:58:31 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at test.ReportGen.VerifyTransaction(ReportGen.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyTransaction -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:test.ReportGen@101eaf6]" name="getResult" is-config="true" duration-ms="0" started-at="2021-04-19T13:58:31 IST" finished-at="2021-04-19T13:58:31 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyTransaction status=FAILURE method=ReportGen.VerifyTransaction()[pri:0, instance:test.ReportGen@101eaf6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="VerifydeleteTransaction()[pri:0, instance:test.ReportGen@101eaf6]" name="VerifydeleteTransaction" duration-ms="0" started-at="2021-04-19T13:58:31 IST" finished-at="2021-04-19T13:58:31 IST">
          <exception class="java.util.NoSuchElementException">
            <message>
              <![CDATA[No Such element ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.util.NoSuchElementException: No Such element 
at test.ReportGen.VerifydeleteTransaction(ReportGen.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.util.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifydeleteTransaction -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:test.ReportGen@101eaf6]" name="getResult" is-config="true" duration-ms="1" started-at="2021-04-19T13:58:31 IST" finished-at="2021-04-19T13:58:31 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifydeleteTransaction status=FAILURE method=ReportGen.VerifydeleteTransaction()[pri:0, instance:test.ReportGen@101eaf6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="SKIP" signature="deleteTransaction()[pri:0, instance:test.ReportGen@101eaf6]" name="deleteTransaction" duration-ms="1" started-at="2021-04-19T13:58:31 IST" finished-at="2021-04-19T13:58:31 IST">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping - This is not ready for testing ]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping - This is not ready for testing 
at test.ReportGen.deleteTransaction(ReportGen.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteTransaction -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:test.ReportGen@101eaf6]" name="getResult" is-config="true" duration-ms="1" started-at="2021-04-19T13:58:31 IST" finished-at="2021-04-19T13:58:31 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=deleteTransaction status=SKIP method=ReportGen.deleteTransaction()[pri:0, instance:test.ReportGen@101eaf6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="afClass()[pri:0, instance:test.ReportGen@101eaf6]" name="afClass" is-config="true" duration-ms="206" started-at="2021-04-19T13:58:31 IST" finished-at="2021-04-19T13:58:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afClass -->
      </class> <!-- test.ReportGen -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
